backend:
  name: github
  repo: pinkmuse/pinkmuse.github.io
  branch: main
  base_url: https://pinkmuse-blog-oauth.vercel.app
  auth_endpoint: api/auth

locale: "zh_Hans"

media_folder: "source/images"
public_folder: "/images"

collections:
  - name: "posts"
    label: "文章"
    label_singular: "文章"
    folder: "source/_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
      preview: false
    fields:
      - { label: "标题", name: "title", widget: "string" }
      - { label: "发布日期", name: "date", widget: "datetime", format: "YYYY-MM-DD HH:mm:ss" }
      - { label: "标签", name: "tags", widget: "list", required: false }
      - { label: "分类", name: "categories", widget: "list", required: false }
      - { label: "正文", name: "body", widget: "markdown" }

  - name: "pages"
    label: "页面"
    label_singular: "页面"
    folder: "source"
    create: true
    nested:
      depth: 100
    editor:
      preview: false
    fields:
      - { label: "标题", name: "title", widget: "string" }
      - { label: "发布日期", name: "date", widget: "datetime", format: "YYYY-MM-DD HH:mm:ss" }
      - { label: "正文", name: "body", widget: "markdown" }
